var questions = {

//level - set - type - question
//Reading / Writing / listening

    "1-1-1-1":{chance1:"Read that sky is blue",chance2:"In other words read, blue is the sky",chance3:"Finally, read the sky is colored blue"},
    "1-1-1-2":{chance1:"Read that the Sun is red",chance2:"In other words, red is the Sun",chance3:"Finally, read the Sun is colored red"},
    "1-1-1-3":{chance1:"Read that the chick is yellow",chance2:"In other words, yellow is the chick",chance3:"Finally, read the chick is colored yellow"},
    "1-1-2-1":{chance1:"Fish can swim",chance2:"Fish swim",chance3:"The fish is swimming"},
    "1-1-2-2":{chance1:"Cats can\'t fly",chance2:"Flying is not for cats",chance3:"Cats don't fly"},
    "1-1-2-3":{chance1:"Dogs bark",chance2:"Barking is what a dog does",chance3:"Dogs make a bark"},
    "1-1-3-1":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-1-3-2":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-1-3-3":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-2-1-1":{chance1:"Read that sky is blue",chance2:"In other words read, blue is the sky",chance3:"Finally, read the sky is colored blue"},
    "1-2-1-2":{chance1:"Read that the Sun is red",chance2:"In other words, red is the Sun",chance3:"Finally, read the Sun is colored red"},
    "1-2-1-3":{chance1:"Read that the chick is yellow",chance2:"In other words, yellow is the chick",chance3:"Finally, read the chick is colored yellow"},
    "1-2-2-1":{chance1:"Fish can swim",chance2:"Fish swim",chance3:"The fish is swimming"},
    "1-2-2-2":{chance1:"Cats can\'t fly",chance2:"Flying is not for cats",chance3:"Cats don't fly"},
    "1-2-2-3":{chance1:"Dogs bark",chance2:"Barking is what a dog does",chance3:"Dogs make a bark"},
    "1-2-3-1":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-2-3-2":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-2-3-3":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-3-1-2":{chance1:"Read that the Sun is red",chance2:"In other words, red is the Sun",chance3:"Finally, read the Sun is colored red"},
    "1-3-1-3":{chance1:"Read that the chick is yellow",chance2:"In other words, yellow is the chick",chance3:"Finally, read the chick is colored yellow"},
    "1-3-2-1":{chance1:"Fish can swim",chance2:"Fish swim",chance3:"The fish is swimming"},
    "1-3-2-2":{chance1:"Cats can\'t fly",chance2:"Flying is not for cats",chance3:"Cats don't fly"},
    "1-3-2-3":{chance1:"Dogs bark",chance2:"Barking is what a dog does",chance3:"Dogs make a bark"},
    "1-3-3-1":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-3-3-2":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-3-3-3":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-4-1-3":{chance1:"Read that the chick is yellow",chance2:"In other words, yellow is the chick",chance3:"Finally, read the chick is colored yellow"},
    "1-4-2-1":{chance1:"Fish can swim",chance2:"Fish swim",chance3:"The fish is swimming"},
    "1-4-2-2":{chance1:"Cats can\'t fly",chance2:"Flying is not for cats",chance3:"Cats don't fly"},
    "1-4-2-3":{chance1:"Dogs bark",chance2:"Barking is what a dog does",chance3:"Dogs make a bark"},
    "1-4-3-1":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-4-3-2":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-4-3-3":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-5-1-3":{chance1:"Read that the chick is yellow",chance2:"In other words, yellow is the chick",chance3:"Finally, read the chick is colored yellow"},
    "1-5-2-1":{chance1:"Fish can swim",chance2:"Fish swim",chance3:"The fish is swimming"},
    "1-5-2-2":{chance1:"Cats can\'t fly",chance2:"Flying is not for cats",chance3:"Cats don't fly"},
    "1-5-2-3":{chance1:"Dogs bark",chance2:"Barking is what a dog does",chance3:"Dogs make a bark"},
    "1-5-3-1":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-5-3-2":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-5-3-3":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-6-1-3":{chance1:"Read that the chick is yellow",chance2:"In other words, yellow is the chick",chance3:"Finally, read the chick is colored yellow"},
    "1-6-2-1":{chance1:"Fish can swim",chance2:"Fish swim",chance3:"The fish is swimming"},
    "1-6-2-2":{chance1:"Cats can\'t fly",chance2:"Flying is not for cats",chance3:"Cats don't fly"},
    "1-6-2-3":{chance1:"Dogs bark",chance2:"Barking is what a dog does",chance3:"Dogs make a bark"},
    "1-6-3-1":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-6-3-2":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-6-3-3":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-7-1-3":{chance1:"Read that the chick is yellow",chance2:"In other words, yellow is the chick",chance3:"Finally, read the chick is colored yellow"},
    "1-7-2-1":{chance1:"Fish can swim",chance2:"Fish swim",chance3:"The fish is swimming"},
    "1-7-2-2":{chance1:"Cats can\'t fly",chance2:"Flying is not for cats",chance3:"Cats don't fly"},
    "1-7-2-3":{chance1:"Dogs bark",chance2:"Barking is what a dog does",chance3:"Dogs make a bark"},
    "1-7-3-1":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-7-3-2":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-7-3-3":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-8-1-3":{chance1:"Read that the chick is yellow",chance2:"In other words, yellow is the chick",chance3:"Finally, read the chick is colored yellow"},
    "1-8-2-1":{chance1:"Fish can swim",chance2:"Fish swim",chance3:"The fish is swimming"},
    "1-8-2-2":{chance1:"Cats can\'t fly",chance2:"Flying is not for cats",chance3:"Cats don't fly"},
    "1-8-2-3":{chance1:"Dogs bark",chance2:"Barking is what a dog does",chance3:"Dogs make a bark"},
    "1-8-3-1":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-8-3-2":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-8-3-3":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-9-1-3":{chance1:"Read that the chick is yellow",chance2:"In other words, yellow is the chick",chance3:"Finally, read the chick is colored yellow"},
    "1-9-2-1":{chance1:"Fish can swim",chance2:"Fish swim",chance3:"The fish is swimming"},
    "1-9-2-2":{chance1:"Cats can\'t fly",chance2:"Flying is not for cats",chance3:"Cats don't fly"},
    "1-9-2-3":{chance1:"Dogs bark",chance2:"Barking is what a dog does",chance3:"Dogs make a bark"},
    "1-9-3-1":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-9-3-2":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"},
    "1-9-3-3":{chance1:"The sky is blue",chance2:"Blue is the sky",chance3:"The sky is colored blue"}
}


  export default questions